### PR TITLE
Defaults/calculated fields

### PR DESCRIPTION
**Pull request by joshowen**
And only calculate defaults if they aren't set already.

We've found this very helpful, let me know what you guys think.  Obviously it requires some documentation.

### CODE REVIEW

**Comment by joshowen** [comment]
This incorporates https://github.com/jlafon/PynamoDB/pull/48

**Comment by joshowen** [comment]
We've been using this as follows:

    class Position(pynamodb.models.Model):
        portfolio_id = NumberAttribute()
        position_date = DateAttribute()
        status = NumberAttribute(null=True)
        portfolio_date = BinaryAttribute(hash_key=True, default=lambda x: to_dated_attribute(x.position_date, x.portfolio_id))
        most_current = BooleanAttribute(null=True, calculator=lambda x: x.status == PositionStatus.MOST_CURRENT.value or None)

By encapsulating this logic in the model, we've been able to simplify a lot of our Position creation code.
* most_current is calculated on every object save
* portfolio_date is calculated at object creation

**Comment by joshowen** [comment]
@jlafon any thoughts

**Comment by jlafon** [comment]
@joshowen That really makes for succinct code! Can we add some tests?

**Comment by pappacena** [comment]
+1

**Comment by joshowen** [comment]
I'll try to add some tests this week or next.

**Comment by garrettheel** [comment]
Reopening with new default branch

**Pull request closed without merging**
