### PR TITLE
Handle attributes that cannot be retrieved by getattr. Fixes #104

### LINKED ISSUE #104: Another crash caused by zope.interface
Similar to #71

This one appear when using an index, the crash is in Model._get_indexes() 

``` python
Exception: AttributeError: __provides__

Exception class: AttributeError

Exception message: __provides__

Backtrace:
filename: "/xxx/local/lib/python2.7/site-packages/paste/deploy/config.py" line: 291 function: "__call__" text/code: "return self.app(environ, start_response)" 
filename: "/xxx/local/lib/python2.7/site-packages/wsgicors.py" line: 197 function: "__call__" text/code: "return self.application(environ, custom_start_response)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/router.py" line: 242 function: "__call__" text/code: "response = self.invoke_subrequest(request, use_tweens=True)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/router.py" line: 217 function: "invoke_subrequest" text/code: "response = handle_request(request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid_metrics/tween.py" line: 24 function: "performance_tween" text/code: "response = handler(request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/tweens.py" line: 21 function: "excview_tween" text/code: "response = handler(request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid_exclog/__init__.py" line: 115 function: "exclog_tween" text/code: "_handle_error(request, getLogger, get_message)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid_exclog/__init__.py" line: 111 function: "exclog_tween" text/code: "return handler(request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/router.py" line: 163 function: "handle_request" text/code: "response = view_callable(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 596 function: "__call__" text/code: "return view(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 329 function: "attr_view" text/code: "return view(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 305 function: "predicate_wrapper" text/code: "return view(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 245 function: "_secured_view" text/code: "return view(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 355 function: "rendered_view" text/code: "result = view(context, request)" 
filename: "/xxx/local/lib/python2.7/site-packages/pyramid/config/views.py" line: 491 function: "_class_view" text/code: "response = getattr(inst, attr)()" 
filename: "/xxx/local/lib/python2.7/site-packages/royal/views.py" line: 44 function: "index" text/code: "result = func(self.context.index_schema(query_params))" 
filename: "/xxx/local/lib/python2.7/site-packages/xxxx/resources.py" line: 286 function: "index" text/code: "devices = Device.get_devices_by_account(self.project_id, account_id)" 
filename: "/xxx/local/lib/python2.7/site-packages/xxxx/device.py" line: 67 function: "get_devices_by_account" text/code: "cls._get_devices_by_account(project_id, account_id)]" 
filename: "/xxx/local/lib/python2.7/site-packages/pynamodb/models.py" line: 521 function: "query" text/code: "cls._get_indexes()" 
filename: "/xxx/local/lib/python2.7/site-packages/pynamodb/models.py" line: 922 function: "_get_indexes" text/code: "item_cls = getattr(getattr(cls, item), "__class__", None)" 
```

### PR DESCRIPTION
**Pull request by jpinner-lyft**

### CODE REVIEW

**Comment by jpinner-lyft** [comment]
@garrettheel @jmphilli any idea why we do:
```
cls = getattr(item, '__class__', None)
issubclass(cls, classinfo)
```
instead of
```
issubclass(item, classinfo)
```

**Comment by jpinner-lyft** [comment]
Some comments while looking at the history from #280:
- previous implementations used `issubclass` directly and `type(cls)`
- inspect `getmembers` has an identical implementation for 2.7+

**Comment by garrettheel** [comment]
@jpinner-lyft I don't know, to be honest. It does seem like a round-a-bout away to do it, so I'd guess there was a good reason for it at the time. Whether that's still the case, I'm not sure

**Comment by jpinner-lyft** [comment]
I didn't actually change the code to `isinstance` yet -- something I might test and do with the 4.0.0 release just in case there is some python 2.6 weirdness.

**Pull request merged**
