### PR TITLE
Remove default region

### LINKED ISSUE #211: Use region from aws configuration by default
It would be nice if pynamodb used the region I have in my ~/.aws/credentials file by default. That's the behavior I get from boto and the aws cli. Instead, pynamodb tables that don't have a region explicitly stated always go to us-east-1.

### PR DESCRIPTION
**Pull request by jalaziz**
Allow the default region to be determined by botocore.

Boto supports loading configuration and credentials from various
providers with a deined order of preference (e.g. environment variables,
config files, metadata service, etc). By hardcoding the defualt region
as us-east-1, we were preventing boto from looking up the correct region
dynamically as one might expect when using the AWS CLI or SDKs.

This change ensures that region configuration is aligned with AWS SDKs
and tables are not unexpectedly created in the wrong region because the
default was not overriden.

This is a breaking change!

Fixes #211

### CODE REVIEW

**Review by ikonst — APPROVED** [review]

**Comment by ikonst** [comment]
I wonder if we should bump version to 6.0a1 at this point.

**Comment by jalaziz** [comment]
Fixed some failing integration tests that starting failing after I changed my local AWS credentials config.

**Comment by jalaziz** [comment]
@ikonst anything I need to do to get the workflow running and this PR mergeD?

**Comment by jalaziz** [comment]
@ikonst sorry, need to unblock the tests again :(. Hopefully they pass now, had to set an environment variable to set a default region since the tests are not running in an AWS environment.

**Comment by jalaziz** [comment]
Thanks! Tests should be stable now.

Please let me know if there's anything else needed to get this merged 😃

**Comment by ikonst** [comment]
@garrettheel I'd like to merge this. Should we consider this compatibility-breaking and bump to 6.x pre-release before or after merging this?

**Comment by garrettheel** [comment]
> @garrettheel I'd like to merge this. Should we consider this compatibility-breaking and bump to 6.x pre-release before or after merging this?

Yep, this will be part of 6.x and we'll call it out as a breaking change.

Thanks @jalaziz for contributing!

**Pull request merged**
