### PR TITLE
Make sessions threadsafe

### PR DESCRIPTION
**Pull request by AusIV**
I ran into the thread safety issue described here:

https://github.com/jlafon/PynamoDB/issues/153

According to boto3's docs, each thread should have its own session instance:

http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading

I resolved this by modifying the session property on the connection
class. It makes self._session into a thread local variable, and
attaches a session to self._session.session. The session property still
has the same behavior, but now it's creating a session on a
per-connection-per-thread basis instead of just on a per-thread basis.

This issue was intermittent to begin with, and I hadn't figured out a
way to reliably reproduce it, or I would have written a test. It still
passes PynamoDB's unit tests, and I haven't run into the thread safety
issue described in #153 since I've been running the patched version.

### CODE REVIEW

**Comment by AusIV** [comment]
Not sure why the checks failed on Python 2.6. It doesn't look like it even executed the tests.

**Comment by garrettheel** [comment]
Reopening with new default branch

**Comment by victoreufrasio** [comment]
I've added a comment in issue #153 that shows how to reproduce this error.

**Comment by jpinner-lyft** [comment]
replaced by #393

**Pull request closed without merging**
