### PR TITLE
fix batch operations docs to use the Thread model in the example code

### PR DESCRIPTION
**Pull request by mattjegan**
The batch operations docs were using the `TestModel` class which is not explained in this section of the docs. I believe the example code was supposed to use the `Thread` class anyway so I have updated it accordingly.

### CODE REVIEW

**Comment by ikonst** [comment]
(CI fails due to https://github.com/pynamodb/PynamoDB/pull/606)

**Comment by ikonst** [comment]
could you please
```
git fetch
git merge upstream/master
git push
```
?

**Comment by mattjegan** [comment]
@ikonst No worries, I've updated my branch

**Comment by ikonst** [comment]
Thanks @mattjegan!

**Pull request merged**
