### PR TITLE
add a test for version attribute

### PR DESCRIPTION
**Pull request by hallie**
I've been seeing an issue where if a model inherits from a base class that already has `VersionAttribute` defined, it will raise an error (even if it doesn't attempt to redefine the attribute). So updating the logic to check if the "duplicate" version attribute has the same name (which means its not actually being redefined)

### CODE REVIEW

**Comment by ikonst** [comment]
eek, dynamodb-local crashed

**Comment by ikonst** [comment]
@hallie can you merge master and retry? it crashes for no fault of yours, travis-ci just upgraded the jdk to a version that's too new for Amazon

**Comment by Yaronn44** [comment]
@hallie Would be cool if this could be merge. I'm really needing this right now

**Comment by lukedeo** [comment]
+1 🙂

**Review by jmphilli — APPROVED** [review]

**Review by jpinner-lyft — APPROVED** [review]

**Pull request merged**
