### PR TITLE
Skip null check when deletion

### PR DESCRIPTION
**Pull request by Surgo**
Not needed null check in deletion.

```
class Foo(GlobalSecondaryIndex):
   foo = attributes.UnicodeAttribute(hash_key=True)
   created = attributes.UTCDateTimeAttribute(range_key=True)

class Bar(Model):
    id = attributes.UnicodeAttribute(hash_key=True)
    buzz = attributes.UnicodeAttribute()

    foo = attributes.UnicodeAttribute()
    created = attributes.UTCDateTimeAttribute()   
    foo_index = Foo()

with Bar.batch_write() as batch:
    for bar in Bar.foo_index.query('foo', created_lt=datetime.now() - timedelta(days=365)):
        batch.delete(bar)
```

Following error occurred

```
ValueError: Attribute 'buzz' cannot be None
```

### CODE REVIEW

**Comment by garrettheel** [comment]
Thanks for contributing! Can you add a test for this? Otherwise looks good.

**Comment by garrettheel** [comment]
Reopening with new default branch

**Comment by Surgo** [comment]
oooooooops. I'll write test :(

**Comment by Surgo** [comment]
Thank you @jmphilli !!1

**Pull request closed without merging**
