### PR TITLE
Use ujson if its available

### PR DESCRIPTION
**Pull request by joshowen**
If you have it, might as well monkey patch botocore.vendored.requests to use it too, but thats out of scope.

https://github.com/kennethreitz/requests/issues/1595

### CODE REVIEW

**Comment by danielhochman** [comment]
https://github.com/jlafon/PynamoDB/blob/33eb91a40ee252525871fa1ce0e47cf6b002ad17/pynamodb/connection/base.py#L238

**Comment by joshowen** [comment]
That is where the monkey patching mentioned above comes in.

**Comment by danielhochman** [comment]
we don't need to patch though, why not call json.loads(request.text)?

**Comment by danielhochman** [comment]
+1 from me

**Comment by joshowen** [comment]
@jlafon any thoughts

**Comment by joshowen** [comment]
Thoughts on merging this in?  I'm happy to update the branch.  We've been using this in production for a while.

**Comment by danielhochman** [comment]
@joshowen definitely. let's take advantage of the new global config introduced in 1.6.0 and allow you to globally patch in whatever json parser you want, defaulting to the built-in json.

let me know if you have any questions.

**Pull request closed without merging**
