### PR TITLE
Support AWS session token

### LINKED ISSUE #501: There is no mechanism for passing a session token
Using STS, I should be able to assume a role and pass the `aws_access_key_id` `aws_secret_access_key` and `session_token` to my model. Currently there is no mechanism to pass the session_token to a Model (without mucking with env variables)

### PR DESCRIPTION
**Pull request by julienduchesne**
Fixes #501 

Sample code:
```
sts_client = boto3.client("sts")
role_object = sts_client.assume_role(RoleArn=role_arn, RoleSessionName="role_name", DurationSeconds=BOTO3_CLIENT_DURATION)
role_credentials = role_object["Credentials"]

class MyModel(Model):
    class Meta:
        table_name = "table_name"
        aws_access_key_id = role_credentials["AccessKeyId"]
        aws_secret_access_key = role_credentials["SecretAccessKey"]
        aws_session_token = role_credentials["SessionToken"]

    hash = UnicodeAttribute(hash_key=True)
    range = UnicodeAttribute(range_key=True)
```

### CODE REVIEW

**Comment by julienduchesne** [comment]
Any update on this?

**Comment by ikonst** [comment]
@julienduchesne I'll try to get another reviewer today or tomorrow.

**Comment by julienduchesne** [comment]
Here you go @garrettheel

**Comment by marcoberb** [comment]
Hi, using this code how do you manage aws_session_token expiration? Doesn't seems that PynamoDB lib handles session refresh...

**Comment by kanghuiliu-wyze** [comment]
any follow-up on the session refresh?

**Pull request merged**
