### PR TITLE
Update condition type to handle Optional bools

### PR DESCRIPTION
**Pull request by Luis-Palacios**
Deals with #787 

Currently when calling any method that uses Condition as the type for one of it's argument eg: range_key_condition in query method mypy will complain if you pass something like `Model.field == 'somevalue'` or any other comparison that directly returns bool such as <, >, etc.. 

It is only happy if you pass something like `Model.field.startswith('somevalue')`  since that actually return an Condition instance. 

Given that the actual function actually handles ==, <, > This PR augment the type for conditions to handle both condition and bools
Update condition type to allow bool

### CODE REVIEW

**Comment by jpinner-lyft** [comment]
This isn't quite right -- these APIs do not take booleans.

The model comparisons (<, >, etc.) return Condition expressions by operator overloading:
https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/expressions/operand.py#L51-L79

My suspicion is that mypy does understand the overloading.

**Comment by Luis-Palacios** [comment]
Haa I see, I'll check on mypy side if there a way to let it know about operator overloading

**Comment by Luis-Palacios** [comment]
So browsing trough mypy issues I realized they expect for `__eq__` to always return bool see: https://github.com/python/mypy/issues/6710#issuecomment-485580032

So I can't think of a good solution to keep `Model.prop == 'value'` as a possible argument while keeping mypy happy.

Only workarounds I can see are:
1. Use Any like so: `condition: Any = Model.prop == request.user.tenant_id` and then pass condition as argument, I have checked this work
2. Use cast if you want to keep type safety `condition = cast(Condition, Model.prop == 'somevalue')`
3. Accept my PR, but this would actually be tricky since is not really a boolean what the API uses

**Comment by ikonst** [comment]
@Luis-Palacios We happen to have a test for that:
https://github.com/pynamodb/PynamoDB/blob/c414d108e4c853d6ce0dec19780406a90bdefb87/tests/test_mypy.py#L32-L33

Does this test happen to miss something?

**Comment by Luis-Palacios** [comment]
It's on my side see #787 for more details.

We can forget about this

**Pull request closed without merging**
